language: node_js

sudo: false

node_js:
  - '11'
  - '10'
  - '9'
  - '8'

before_install:
  #  - npm install codecov -g
  - npm update

install:
  - npm install

script:
  #  - npm test && codecov
  - npm run test:cov
#  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
